version: "3.8"

services:
  balance-bot:
    build: .
    container_name: balance-bot
    restart: unless-stopped
    env_file: .env
    environment:
      SIMPLEFIN_ACCESS_URL: "${SIMPLEFIN_ACCESS_URL}"
      POLL_CRON_EXPRESSION: "${POLL_CRON_EXPRESSION:-*/5 * * * *}"
      ACCOUNT_NOTIFICATION_TARGETS: "${ACCOUNT_NOTIFICATION_TARGETS:-}"
      APPRISE_API_URL: "${APPRISE_API_URL:-http://apprise:8000/notify}"
    volumes:
      - ./data:/app/data
    depends_on:
      - apprise

  apprise:
    image: ghcr.io/linuxserver/apprise-api:latest
    container_name: apprise
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./apprise:/config
    ports:
      - "8000:8000"
